from decimal import Decimal

from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship,
)

# Base class that all models inherit from (defined in connection.py)
from database.connection import Base


# Top-level categories that group services together
class Section(Base):
    __tablename__ = "Section"

    # Unique ID for each section, auto-generated by the database
    section_id: Mapped[int] = mapped_column(
        "SectionID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Section name, must be unique so no two sections share a name
    section_name: Mapped[str] = mapped_column(
        "SectionName",
        String(100),
        nullable=False,
        unique=True,
    )

    # One section has many services (link to the Service table)
    services: Mapped[list["Service"]] = relationship(
        back_populates="section",
    )


# Each service belongs to exactly one section
class Service(Base):
    __tablename__ = "Service"

    # Prevent duplicate service names within the same section
    __table_args__ = (
        UniqueConstraint(
            "SectionID",
            "ServiceName",
            name="uq_service_section_name",
        ),
    )

    # Unique ID for each service
    service_id: Mapped[int] = mapped_column(
        "ServiceID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Links this service to its parent section
    section_id: Mapped[int] = mapped_column(
        "SectionID",
        Integer,
        ForeignKey("Section.SectionID"),
        nullable=False,
    )

    service_name: Mapped[str] = mapped_column(
        "ServiceName",
        String(150),
        nullable=False,
    )

    # The section this service belongs to (reverse link)
    section: Mapped["Section"] = relationship(
        back_populates="services",
    )

    # One service can have many measurement records over time
    measurement_records: Mapped[
        list["MeasurementRecord"]
    ] = relationship(
        back_populates="service",
    )


# One record = one service measured in a specific year and period
class MeasurementRecord(Base):
    __tablename__ = "MeasurementRecords"

    # A service can only have one record per year+period combination
    __table_args__ = (
        UniqueConstraint(
            "ServiceID",
            "Year",
            "Period",
            name="uq_measurement_service_year_period",
        ),
    )

    # Unique ID for each measurement record
    record_id: Mapped[int] = mapped_column(
        "RecordID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Which service this record measures
    service_id: Mapped[int] = mapped_column(
        "ServiceID",
        Integer,
        ForeignKey("Service.ServiceID"),
        nullable=False,
    )

    # The year the measurement was taken
    year: Mapped[int] = mapped_column(
        "Year",
        Integer,
        nullable=False,
    )

    # The period within the year (e.g. a quarter or half)
    period: Mapped[str] = mapped_column(
        "Period",
        String(20),
        nullable=False,
    )

    # How many people took part in this measurement (defaults to 0)
    participants_count: Mapped[int] = mapped_column(
        "ParticipantsCount",
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
    )

    # Optional free-text notes/review for this record
    review: Mapped[str | None] = mapped_column(
        "Review",
        Text,
        nullable=True,
    )

    # The service this record belongs to (reverse link)
    service: Mapped["Service"] = relationship(
        back_populates="measurement_records",
    )

    # Indicator results tied to this record
    # cascade: deleting the record also deletes its indicator results
    indicator_results: Mapped[
        list["IndicatorResult"]
    ] = relationship(
        back_populates="record",
        cascade="all, delete-orphan",
    )

    # Factor results tied to this record
    # cascade: deleting the record also deletes its factor results
    factor_results: Mapped[
        list["FactorResult"]
    ] = relationship(
        back_populates="record",
        cascade="all, delete-orphan",
    )


# Indicators being tracked, such as CSAT, CES, NPS

# IsFactorBased = True
#   -> current value is calculated from the underlying factor results (e.g. CSAT)
# IsFactorBased = False
#   -> value stands on its own / is entered directly (e.g. CES, NPS, BPS)
class Indicator(Base):
    __tablename__ = "Indicators"

    # Unique ID for each indicator
    indicator_id: Mapped[int] = mapped_column(
        "IndicatorID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Indicator name, must be unique
    indicator_name: Mapped[str] = mapped_column(
        "IndicatorName",
        String(100),
        nullable=False,
        unique=True,
    )

    # The unit the value is measured in (e.g. %, points)
    unit: Mapped[str] = mapped_column(
        "Unit",
        String(30),
        nullable=False,
    )

    # Lowest possible value this indicator can take
    min_value: Mapped[Decimal] = mapped_column(
        "MinValue",
        Numeric(10, 2),
        nullable=False,
    )

    # Highest possible value this indicator can take
    max_value: Mapped[Decimal] = mapped_column(
        "MaxValue",
        Numeric(10, 2),
        nullable=False,
    )

    # True = value comes from factor results, False = entered directly
    is_factor_based: Mapped[bool] = mapped_column(
        "IsFactorBased",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("0"),
    )

    # All results recorded for this indicator across records
    results: Mapped[
        list["IndicatorResult"]
    ] = relationship(
        back_populates="indicator",
    )


# Stores previous, current, and target values for each
# indicator within each measurement record
class IndicatorResult(Base):
    __tablename__ = "IndicatorResults"

    # Each indicator can only appear once per record
    __table_args__ = (
        UniqueConstraint(
            "RecordID",
            "IndicatorID",
            name="uq_indicator_result_record_indicator",
        ),
    )

    # Unique ID for each indicator result
    result_id: Mapped[int] = mapped_column(
        "ResultID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Which measurement record this result belongs to
    record_id: Mapped[int] = mapped_column(
        "RecordID",
        Integer,
        ForeignKey("MeasurementRecords.RecordID"),
        nullable=False,
    )

    # Which indicator this result is for
    indicator_id: Mapped[int] = mapped_column(
        "IndicatorID",
        Integer,
        ForeignKey("Indicators.IndicatorID"),
        nullable=False,
    )

    # Value from the previous period (optional, for comparison)
    prev_value: Mapped[Decimal | None] = mapped_column(
        "PrevValue",
        Numeric(10, 2),
        nullable=True,
    )

    # The value measured this period (required)
    current_value: Mapped[Decimal] = mapped_column(
        "CurrentValue",
        Numeric(10, 2),
        nullable=False,
    )

    # The goal we're aiming for (optional)
    target_value: Mapped[Decimal | None] = mapped_column(
        "TargetValue",
        Numeric(10, 2),
        nullable=True,
    )

    # The record this result belongs to (reverse link)
    record: Mapped["MeasurementRecord"] = relationship(
        back_populates="indicator_results",
    )

    indicator: Mapped["Indicator"] = relationship(
        back_populates="results",
    )


# The seven fixed CSAT factors
# The actual factor names are inserted by seed_data.py
class Factor(Base):
    __tablename__ = "Factors"

    # Unique ID for each factor
    factor_id: Mapped[int] = mapped_column(
        "FactorID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Factor name, must be unique
    factor_name: Mapped[str] = mapped_column(
        "FactorName",
        String(150),
        nullable=False,
        unique=True,
    )

    # Controls the order factors are shown in; must be unique
    display_order: Mapped[int] = mapped_column(
        "DisplayOrder",
        Integer,
        nullable=False,
        unique=True,
    )

    # All results recorded for this factor across records
    results: Mapped[
        list["FactorResult"]
    ] = relationship(
        back_populates="factor",
    )


# CSAT Factor Results
# Stores the result of each factor for each measurement record
class FactorResult(Base):
    __tablename__ = "FactorResults"

    # Each factor can only appear once per record
    __table_args__ = (
        UniqueConstraint(
            "RecordID",
            "FactorID",
            name="uq_factor_result_record_factor",
        ),
    )

    # Unique ID for each factor result
    factor_result_id: Mapped[int] = mapped_column(
        "FactorResultID",
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Which measurement record this result belongs to
    record_id: Mapped[int] = mapped_column(
        "RecordID",
        Integer,
        ForeignKey("MeasurementRecords.RecordID"),
        nullable=False,
    )

    # Which factor this result is for
    factor_id: Mapped[int] = mapped_column(
        "FactorID",
        Integer,
        ForeignKey("Factors.FactorID"),
        nullable=False,
    )

    # Number of valid responses used to calculate this factor's score
    participants_count: Mapped[int | None] = mapped_column(
        "ParticipantsCount",
        Integer,
        nullable=True,
    )

    # Value from the previous period (optional, for comparison)
    prev_value: Mapped[Decimal | None] = mapped_column(
        "PrevValue",
        Numeric(10, 2),
        nullable=True,
    )

    # The value measured this period (required)
    current_value: Mapped[Decimal] = mapped_column(
        "CurrentValue",
        Numeric(10, 2),
        nullable=False,
    )

    # The goal we're aiming for (optional)
    target_value: Mapped[Decimal | None] = mapped_column(
        "TargetValue",
        Numeric(10, 2),
        nullable=True,
    )

    # The record this result belongs to (reverse link)
    record: Mapped["MeasurementRecord"] = relationship(
        back_populates="factor_results",
    )

    # The factor this result is for (reverse link)
    factor: Mapped["Factor"] = relationship(
        back_populates="results",
    )